### ISSUE TITLE
Ios mySilentDataHandle never invoked

### ISSUE THREAD

**Issue by hatemragab** [rafaelsetragni/awesome_notifications_fcm#4]
## **1 - Describe the bug**
in ios mySilentDataHandle never invoked with me 
its Ios bug only the android mySilentDataHandle works good

I have done all steps in this [awesome_notifications_fcm]
my pub yamel is 
```
name: awsoom_nofic_test_hragap
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.24.0
  awesome_notifications: ^0.7.3
  fluttertoast: ^8.0.3
  awesome_notifications_fcm: ^0.7.3
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
```
my code send from my backend is 
```
//
const admin = require('firebase-admin');
// 1. Download a service account key (JSON file) from your Firebase console and add to the example/scripts directory
const serviceAccount = require('./google-services.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});

// 2. Copy the token for your device that is printed in the console on app start (`flutter run`) for the FirebaseMessaging example
const token = 'fPqWFyuvYEPLpd72WcNitt:APA91bEtTAVpwjranLDCKizBMdIbfkvvsnomTRFD8z3wQJk2jxCcYIGmB0cF_9DD6-Utr2IeRMeidkVdJAPzE4Fz2FSnxDznMno_AWJzKXvWHg0aFyO-UcOAKjs1Xim3C-FgirxflNwu';


// 3. From your terminal, root to example/scripts directory & run `npm install`.
// 4. Run `npm run send-message` in the example/scripts directory and your app will receive messages in any state; foreground, background, terminated.
// If you find your messages have stopped arriving, it is extremely likely they are being throttled by the platform. iOS in particular
// are aggressive with their throttling policy.
admin
  .messaging()
  .sendMulticast(
    {
    //comment this to get the message as silent
//      notification:{
//        body:"xx",
//        title:"dff"
//      },
      tokens: [token],
      data: {
        "foo": "foox"
      },
      apns: {
        headers: {
          'apns-push-type': 'background',
          'apns-priority': '5',
          'apns-topic': 'com.example.awsoomNoficTestHragap'
        },
        payload: {
          aps: {
            contentAvailable: true,
          }
        }
      }
    }
  )
  .then((res) => {
    if (res.failureCount) {
      console.log('Failed', res.responses);
    } else {
      console.log('Success');
    }
  })
  .catch((err) => {
    console.log('Error:', err);
  });
```
 i also try the postman collection but it only receives the notification if i set the title and body 
if i delete it nothing happens
please take look about my project i have uploaded it on this repo 

[awesome_notifications_fcm_test](https://github.com/hatemragab/awesome_notifications_fcm_test)
